[package]
name = "entity"
description = "Library that provides entity-like constructs"
categories = ["data-structures"]
version = "0.0.0"
authors = ["Chip Senkbeil <chip@senkbeil.org>"]
edition = "2018"
homepage = "https://github.com/chipsenkbeil/entity-rs"
repository = "https://github.com/chipsenkbeil/entity-rs"
readme = "README.md"
license = "MIT OR Apache-2.0"

[features]
default = ["serde"]
async = ["async-trait"]

[dependencies]
async-trait = { version = "0.1.41", optional = true }
derive_more = { version = "0.99.11", default-features = false, features = ["as_ref", "as_mut", "constructor", "display", "error", "from", "into"] }
serde = { version = "1.0.117", features = ["derive"], optional = true }
strum = { version = "0.19", features = ["derive"] }
