[package]
name = "entity_macros"
description = "Macro library that provides macros to generate entities, queries, and more at compile time."
categories = ["data-structures"]
version = "0.0.0"
authors = ["Chip Senkbeil <chip@senkbeil.org>"]
edition = "2018"
